apiVersion: amlarc.azureml.com/v1alpha1
kind: InstanceType
metadata:
  name: mlinstance
spec:
  nodeSelector:
   AzureMLNode: mlnode
  resources:
    limits:
      cpu: "1"
      nvidia.com/gpu: null
      memory: "2Gi"
    requests:
      cpu: "700m"
      memory: "1500Mi"